# standard build with Maven and push coverage data
name: Build Tests

# trigger build on branches that *should* support both Java 8 and Java 11
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Install dependencies
        run: mvn clean install -DskipTests=true

      - name: Build with Maven
        run: mvn clean install
